[package]
name = "esdt-nft-marketplace"
version = "0.0.0"
authors = ["Mihai Daniel <mihai@xoxno.com>"]
edition = "2018"
publish = false

[lib]
path = "src/marketplace_main.rs"

[dependencies.elrond-wasm]
version = "0.36.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.1"