[package]
name = "esdt-nft-marketplace"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/marketplace_main.rs"

[dependencies.elrond-wasm]
version = "0.29.2"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.2"

[dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
