[package]
name = "xoxno-protocol-meta"
version = "1.0.0"
authors = ["Mihai Daniel <mihai@xoxno.com>"]
edition = "2021"
publish = false

[dependencies.xoxno-protocol]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.1"
default-features = false
